[profile.default]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

